/* DIALOG RESOURCE HEADER FILE */

/*[PDE:ArgsDLG]*/
extern DLGITEM ArgsDLGItems[];
extern DIALOG ArgsDLG;

#define ARGSDLG1 0
#define ARGSDLG2 1

/*[PDE:IconDLG]*/
extern DLGITEM IconDLGItems[];
extern DIALOG IconDLG;

#define ICONDLG1 0
#define ICONDLG2 1

/*[PDE:VolDLG]*/
extern DLGITEM VolDLGItems[];
extern DIALOG VolDLG;

#define VOLDLG1 0
#define VOLDLG2 1
#define VOLDLG3 2
#define VOLDLG4 3
#define VOLDLG5 4
#define VOLDLG6 5

/*[PDE:battDLG]*/

extern DLGITEM battDLGItems[];
extern DIALOG battDLG;

#define BATTDLG1 0
#define BATTDLG2 1
#define BATTDLG3 2
#define BATTDLG4 3
#define BATTDLG5 4
#define BATTDLG6 5
#define BATTDLG7 6
#define BATTDLG8 7
#define BATTDLG9 8
#define BATTDLG10 9

/*[PDE:InfoDLG]*/
extern DLGITEM InfoDLGItems[];
extern DIALOG InfoDLG;

#define INFODLG1 0
#define INFODLG2 1
#define INFODLG4 2
#define INFODLG5 3
#define INFODLG6 4

/*[PDE:OwnerDLG]*/

extern DLGITEM OwnerDLGItems[];
extern DIALOG OwnerDLG;

#define OWNERDLG1 0
#define OWNERDLG2 1
#define OWNERDLG3 2
#define OWNERDLG4 3
#define OWNERDLG5 4
#define OWNERDLG6 5

/*[PDE:AddDLG]*/

extern DLGITEM AddDLGItems[];
extern DIALOG AddDLG;

#define ADDDLG1 0
#define ADDDLG2 1
#define ADDDLG3 2
#define ADDDLG4 3
#define ADDDLG5 4
#define ADDDLG6 5
#define ADDDLG7 6
#define ADDDLG8 7
#define ADDDLG9 8
#define ADDDLG10 9
#define ADDDLG11 10
#define ADDDLG12 11
#define ADDDLG13 12
#define ADDDLG14 13
#define ADDDLG15 14
#define ADDDLG16 15
#define ADDDLG17 16
#define ADDDLG18 17

