/* PAL-DIALOG RESOURCE HEADER FILE */

/*[PDE:Find]*/

extern DLGITEM FindItems[];
extern DIALOG Find;

#define FIND1 0
#define FIND2 1
#define FIND3 2
#define FIND4 3
#define FIND5 4
#define FIND6 5
#define FIND7 6
#define FIND8 7

/*[PDE:criteria]*/

extern DLGITEM criteriaItems[];
extern DIALOG criteria;

#define CRITERIA1 0
#define CRITERIA2 1
#define CRITERIA3 2
#define CRITERIA4 3
#define CRITERIA5 4
#define CRITERIA6 5

